
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: dibya
    url: jdbc:mysql://localhost:3306/bank
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     database-platform: org.hibernate.dialect.MySQLDialect
     hibernate:
            ddl-auto: update
            show_sql: true
            format_sql: true 
          
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: dibyajyoti.panigrahi.dipu@gmail.com
    password: qrhy guqd gcox ogpp
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

            
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081
 
# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  invalid:  Failed
  login: Login Success
  retrive: Retrive success 
  User deleted successfully: User detected
  update: Updated successfully
  retriveOne: Retrive one
